### ISSUE TITLE
NPM release

### ISSUE THREAD

**Issue by Jogai** [primefaces/primevue-sass-theme#1]
I dont know if this is meant to go on npm, but the fact that [this](https://github.com/Riadz/primevue-sass-themes) exists makes it a little confusing. Maybe @riad-rymexp can chime in as well.

**Comment by cagataycivici** [comment]
Hi Jogai, I don't know about that project but I don't see a reason to publish this repo to npm at the moment.

**Comment by Jogai** [comment]
Okay, no problem
