### ISSUE TITLE
New `@layer` implementation

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primevue-sass-theme#24]

**Comment by tugcekucukoglu** [comment]
https://github.com/primefaces/primevue-sass-theme/commit/82bf9cf777f04915e7ec21002ea097df8d6c90d5

**Comment by loxK** [comment]
This broke some things in my app. 

I have a css rule for labels:

```
label {
    color: $tertiaryColor;
}
```

This was superseded by this PrimeVue css rule :

```
.p-float-label > label {
    color: #898989;
}
```

Now that this rule is in a `primevue` layer (a feature I didn't know about). How am I supposed to handle that issue ?
