### ISSUE TITLE
Change :focus to :focus-visible on theme-base button.scss

### ISSUE THREAD

**Issue by dbasilioesp** [primefaces/primevue-sass-theme#32]
This rule `:focus` overwrite extended rules when is used only `:focus-visible`.

https://github.com/primefaces/primevue-sass-theme/blob/ca40239c57691e988f0cc515f76fffe387155f46/theme-base/components/button/_button.scss#L87-L89

**Comment by tugcekucukoglu** [comment]
It's not on our roadmap.

Thank you!
