### ISSUE TITLE
Undefined variable inputFocusOutlineOffset

### ISSUE THREAD

**Issue by jrozanski** [primefaces/primevue-sass-theme#45]
There appears to be only one theme, the `aura-light` that provides this variable, but it is required in the base theme.

```
ERROR  [sass] Undefined variable.
outline-offset: $inputFocusOutlineOffset;
                ^^^^^^^^^^^^^^^^^^^^^^^^
assets/css/theme-base/_mixins.scss 21:21                         focused-input()
```

**Comment by cmavelis** [comment]
note that this breaks when following the "Compile SCSS Manually" portion of the docs

flipping through compiled themes, seems like this value should default to 0 somewhere in the base theme

**Comment by tugcekucukoglu** [comment]
Fixed internally.

Thank you!

**Comment by MikaelFields** [comment]
this variable "$**inputFocusOutlineOffset**" seems to be absent in https://github.com/primefaces/primeng-sass-theme/releases/tag/17.12.0, I cannot make my project work :(

**Comment by SeanW22** [comment]
I'm having the same issue as @MikaelFields after:  
"sass --update primeng-theme\themes\mytheme\theme.scss:Dev\theme.css"

Error: Undefined variable.
   ╷
21 │     outline-offset: $inputFocusOutlineOffset;
   │                     ^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  ..\..\primeng-theme\theme-base\_mixins.scss 21:21                         focused-input()
  ..\..\primeng-theme\theme-base\components\input\_autocomplete.scss 22:13  @import
  ..\..\primeng-theme\theme-base\_components.scss 10:13                     @import
  ..\..\primeng-theme\themes\mytheme\theme.scss 3:9                         root stylesheet
